-- Auto-generated (5 challenges, 3 advocate posts)
-- advocate_id in posts must exist in advocate_profiles before running post seeds.

INSERT INTO public.beauty_challenges (
  id, name, description, challenge_type, duration_days, start_date, end_date,
  cover_image_url, prize, sponsor_brand_id, ftc_disclosure_required, active, participant_count, daily_prompts
) VALUES
  ('c0000001-0003-4003-8003-000000000001'::uuid, '7 Days of Self-Care', 'Body-positive rituals for rest, hydration, and joy — no transformation goals, no before/after pressure.', 'self_care', 7, '2026-05-18', '2026-05-24', NULL, 'Featured on Sif''s Gold community spotlight', NULL, false, true, 128, '[{"day":1,"title":"Pause","prompt":"Take five minutes away from screens — breathe, stretch, or sip water."},{"day":2,"title":"Hydrate","prompt":"Drink an extra glass of water and notice how your body feels."},{"day":3,"title":"Gentle touch","prompt":"Apply hand cream or oil slowly — a small act of care for you."},{"day":4,"title":"Boundary","prompt":"Say no to one thing that drains you today."},{"day":5,"title":"Joy","prompt":"Do something that makes you smile with zero productivity goal."},{"day":6,"title":"Rest","prompt":"Protect your sleep window tonight — dim lights, calm routine."},{"day":7,"title":"Gratitude","prompt":"Name three things your body did for you this week."}]'::jsonb),
  ('c0000002-0003-4003-8003-000000000002'::uuid, 'Color Theory Mastery', 'Build formulation confidence with daily study — skill-focused, not appearance-focused.', 'skill_building', 14, '2026-05-18', '2026-05-31', NULL, 'Study guide bundle shout-out', NULL, false, true, 84, '[{"day":1,"title":"Level","prompt":"Review level vs tone on a swatch chart for 10 minutes."},{"day":2,"title":"Underlying pigment","prompt":"Sketch warm vs cool underlying pigment notes."},{"day":3,"title":"Consult","prompt":"Practice explaining one color choice in client-friendly language."},{"day":4,"title":"Strand test","prompt":"Plan a strand test — document timing, not results photos."},{"day":5,"title":"Grey blend","prompt":"Study one grey-blending approach from manufacturer education."},{"day":6,"title":"Correction map","prompt":"Map a color correction flowchart on paper."},{"day":7,"title":"Rest day","prompt":"Rest your eyes — revisit notes tomorrow."},{"day":8,"title":"Formulation","prompt":"Write a formula for a demi refresh without photos."},{"day":9,"title":"Share","prompt":"Teach a peer one concept you learned this week."},{"day":10,"title":"Celebrate craft","prompt":"Celebrate a technique win — not a physical change."}]'::jsonb),
  ('c0000003-0003-4003-8003-000000000003'::uuid, 'Creative Chair Moments', 'Document craft, tools, and process — celebrate artistry without comparison framing.', 'creative', 10, '2026-05-15', '2026-05-24', NULL, NULL, NULL, false, true, 56, '[{"day":1,"title":"Tools flat lay","prompt":"Photograph your tools setup — no faces required."},{"day":2,"title":"Texture","prompt":"Close-up of texture you created (with consent)."},{"day":3,"title":"Palette","prompt":"Share a color palette that inspires today''s work."},{"day":4,"title":"Process","prompt":"Mid-process shot — show the work, not a reveal."},{"day":5,"title":"Education","prompt":"Share one tip you wish you knew as a student."}]'::jsonb),
  ('c0000004-0003-4003-8003-000000000004'::uuid, 'Community Kindness Chain', 'Uplift another pro or client — kindness only, no critique of bodies.', 'community', 5, '2026-05-18', '2026-05-22', NULL, NULL, NULL, false, true, 201, '[{"day":1,"title":"Shout-out","prompt":"Tag a colleague whose work you respect."},{"day":2,"title":"Review","prompt":"Leave a thoughtful review for a pro you booked."},{"day":3,"title":"Mentor","prompt":"Send encouragement to a student in your network."},{"day":4,"title":"Client care","prompt":"Share how you make clients feel safe in your chair."},{"day":5,"title":"Pay it forward","prompt":"Offer a small kindness with no expectation back."}]'::jsonb),
  ('c0000005-0003-4003-8003-000000000005'::uuid, 'Mindful Hands Week', 'Ergonomics and hand care for long days — wellness for pros.', 'self_care', 7, '2026-05-04', '2026-05-10', NULL, NULL, NULL, false, false, 312, '[{"day":1,"title":"Stretch","prompt":"Two-minute wrist and forearm stretch between clients."},{"day":2,"title":"Posture","prompt":"Reset chair height and posture checklist."}]'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  active = EXCLUDED.active,
  participant_count = EXCLUDED.participant_count,
  daily_prompts = EXCLUDED.daily_prompts;

INSERT INTO public.advocate_posts (
  id, advocate_id, post_type, title, body, image_urls, video_url,
  linked_brand_deal_id, ftc_disclosure_text, status, published_at, view_count, like_count
) VALUES
  ('p0000001-0004-4004-8004-000000000001'::uuid, '00000000-0000-4000-8000-000000000099'::uuid, 'tip', 'Consultation questions that build trust', 'Ask what maintenance window feels realistic — not what they wish they looked like. Clients open up when goals are collaborative.', ARRAY[]::text[], NULL, NULL, NULL, 'published', '2026-05-18T18:45:58.634Z'::timestamptz, 420, 38),
  ('p0000002-0004-4004-8004-000000000002'::uuid, '00000000-0000-4000-8000-000000000099'::uuid, 'tutorial', 'Gloss refresh without over-processing', 'A demi refresh can revive tone between full services — always strand test and document timing.', ARRAY[]::text[], NULL, NULL, NULL, 'published', '2026-05-18T18:45:58.634Z'::timestamptz, 310, 27),
  ('p0000003-0004-4004-8004-000000000003'::uuid, '00000000-0000-4000-8000-000000000099'::uuid, 'brand_partner', 'Why I reach for this bond builder between services', 'Honest routine on damaged hair — focused on integrity, not transformation promises.', ARRAY[]::text[], NULL, NULL, 'Paid partnership with Partner Brand. #ad #partner Posted on Sif''s Gold. This disclosure is provided in accordance with the U.S. FTC Endorsement Guides (16 CFR Part 255).', 'published', '2026-05-18T18:45:58.634Z'::timestamptz, 890, 64)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  status = EXCLUDED.status,
  ftc_disclosure_text = EXCLUDED.ftc_disclosure_text;
