import "server-only";

import type { CampaignContract } from "@/lib/brand-deals/types";

export function buildContractDocumentHtml(params: {
  campaignTitle: string;
  brandName: string;
  advocateName: string;
  contract: Pick<
    CampaignContract,
    "compensation_amount" | "compensation_type" | "contract_terms" | "signed_by_brand" | "signed_by_advocate" | "brand_signed_at" | "advocate_signed_at"
  >;
  ftcTemplate: string;
}): string {
  const { contract, campaignTitle, brandName, advocateName, ftcTemplate } = params;

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"/><title>Brand Deal Contract — ${campaignTitle}</title></head>
<body style="font-family: Georgia, serif; max-width: 720px; margin: 2rem auto; color: #04101E;">
  <h1>Sif's Gold — Brand Deal Agreement</h1>
  <p><strong>Campaign:</strong> ${campaignTitle}</p>
  <p><strong>Gold Partner:</strong> ${brandName}</p>
  <p><strong>Sif's Advocate:</strong> ${advocateName}</p>
  <h2>Compensation</h2>
  <p>$${contract.compensation_amount} (${contract.compensation_type}) — 70% paid to advocate on approved deliverables; 30% platform fee per marketplace policy.</p>
  <h2>FTC Disclosure (16 CFR Part 255)</h2>
  <pre style="background:#F5EFE0;padding:1rem;">${ftcTemplate}</pre>
  <h2>Signatures</h2>
  <p>Brand signed: ${contract.signed_by_brand ? contract.brand_signed_at ?? "yes" : "pending"}</p>
  <p>Advocate signed: ${contract.signed_by_advocate ? contract.advocate_signed_at ?? "yes" : "pending"}</p>
  <p style="font-size:12px;color:#666;">Generated by Sif's Gold Brand Deal Marketplace. Click-through signatures include IP and timestamp records.</p>
</body>
</html>`;
}

export function contractPdfPath(contractId: string): string {
  return `brand-deals/contracts/${contractId}.html`;
}
