/**
 * Career paths seed — BLS OEWS May 2023 national medians where available.
 * https://www.bls.gov/oes/
 */
import { PATH_IDS, ROLE_IDS } from "@/lib/career-paths/constants";
import type { CareerRole, EndRole, StartingPoint } from "@/types/career-paths";

export type SeedMilestone = {
  milestone_order: number;
  name: string;
  description: string;
  estimated_duration_months: number;
  estimated_cost: number;
  requirements: string[];
  typical_outcomes: string[];
  role_id?: string;
};

export type SeedPath = {
  id: string;
  starting_point: StartingPoint;
  end_role: EndRole;
  name: string;
  description: string;
  estimated_total_years: number;
  estimated_total_investment: number;
  order_index: number;
  milestones: SeedMilestone[];
};

const BLS = "https://www.bls.gov/oes/current/";

export const SEED_ROLES: Omit<CareerRole, "id">[] = [
  {
    name: "Licensed Cosmetologist",
    category: "hair",
    description: "Provides haircutting, coloring, styling, and basic chemical services within state scope.",
    median_annual_salary: 35080,
    salary_range_low: 22600,
    salary_range_high: 55000,
    bls_source_link: `${BLS}oes395012.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_cosmetology_license"],
    required_education:
      "State-approved cosmetology program (typically 1,000–1,600 clock hours depending on jurisdiction).",
    typical_continuing_education: "Renewal CE per state board (often 4–16 hours biennially).",
    specialty_certifications: ["Manufacturer color certifications", "Texture / extension modules"],
    career_advancement: "Color specialist, salon lead, suite rental, educator, or salon ownership.",
    icon: "Scissors",
  },
  {
    name: "Barber",
    category: "hair",
    description: "Men's grooming, fades, beard design, and straight-razor services where permitted.",
    median_annual_salary: 38420,
    salary_range_low: 24000,
    salary_range_high: 62000,
    bls_source_link: `${BLS}oes395011.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_barber_or_cosmetology_license"],
    required_education: "Barber or cosmetology program per state (often 1,000–1,500 hours).",
    typical_continuing_education: "Bloodborne pathogen refreshers; razor endorsement where required.",
    specialty_certifications: ["Straight razor certification", "Fade / texture workshops"],
    career_advancement: "Shop lead, mobile barber, studio owner, or platform educator.",
    icon: "Scissors",
  },
  {
    name: "Licensed Esthetician",
    category: "skin",
    description: "Facials, skin analysis, hair removal, and foundational device services within scope.",
    median_annual_salary: 43140,
    salary_range_low: 28000,
    salary_range_high: 72000,
    bls_source_link: `${BLS}oes395094.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_esthetics_license"],
    required_education: "Esthetics program (often 600–1,200 hours by state).",
    typical_continuing_education: "State renewal CE; device training per manufacturer.",
    specialty_certifications: ["Chemical peel tiers", "Microcurrent / LED device certs"],
    career_advancement: "Med spa technician, spa lead, or esthetics educator.",
    icon: "Sparkles",
  },
  {
    name: "Nail Technician",
    category: "nails",
    description: "Manicures, pedicures, enhancements, and nail health-focused services.",
    median_annual_salary: 32270,
    salary_range_low: 22000,
    salary_range_high: 48000,
    bls_source_link: `${BLS}oes395092.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_manicurist_or_nail_license"],
    required_education: "Nail technology program (often 300–600 hours).",
    typical_continuing_education: "Sanitation refreshers; e-file safety courses.",
    specialty_certifications: ["Hard gel / acrylic manufacturer certs", "Nail art masterclasses"],
    career_advancement: "Nail art specialist, suite owner, or social educator.",
    icon: "Sparkles",
  },
  {
    name: "Massage Therapist (LMT)",
    category: "massage",
    description: "Therapeutic massage in spa, clinical, or independent practice settings.",
    median_annual_salary: 55310,
    salary_range_low: 32000,
    salary_range_high: 79000,
    bls_source_link: `${BLS}oes311131.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_massage_license"],
    required_education: "Massage therapy program (typically 500–1,000 hours).",
    typical_continuing_education: "Ethics and pathology refreshers per state.",
    specialty_certifications: ["Sports massage", "Medical / orthopedic massage CE"],
    career_advancement: "Clinical specialist, spa director, or private practice owner.",
    icon: "Hand",
  },
  {
    name: "Tattoo Artist",
    category: "tattoo",
    description: "Custom tattoo application under local licensure and apprenticeship standards.",
    median_annual_salary: 57990,
    salary_range_low: 28000,
    salary_range_high: 95000,
    bls_source_link: `${BLS}oes271013.htm`,
    salary_data_year: 2023,
    required_license_types: ["local_tattoo_registration", "bloodborne_pathogen_training"],
    required_education:
      "Apprenticeship (typical 1–3 years). BLS reports Fine Artists; tattoo wages vary widely by market.",
    typical_continuing_education: "Annual BBP renewal; local health department updates.",
    specialty_certifications: ["Style specialties (realism, blackwork) via mentorship"],
    career_advancement: "Private studio, convention circuit, or shop ownership.",
    icon: "PenTool",
  },
  {
    name: "Hair Color Specialist",
    category: "hair",
    description: "Advanced formulation, corrective color, and lightening services.",
    median_annual_salary: 38000,
    salary_range_low: 26000,
    salary_range_high: 72000,
    bls_source_link: `${BLS}oes395012.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_cosmetology_license"],
    required_education: "Licensed cosmetologist plus advanced color CE.",
    typical_continuing_education: "Manufacturer academies; corrective color workshops.",
    specialty_certifications: ["Balayage", "Vivid fashion color", "Color correction"],
    career_advancement: "Balayage expert, platform artist, or color educator.",
    icon: "Palette",
  },
  {
    name: "Salon Manager",
    category: "business",
    description: "Floor leadership, scheduling, retail, and service standards for a salon team.",
    median_annual_salary: 38760,
    salary_range_low: 28000,
    salary_range_high: 58000,
    bls_source_link: `${BLS}oes391022.htm`,
    salary_data_year: 2023,
    required_license_types: ["cosmetology_license_recommended"],
    required_education: "License plus management / business CE or associate coursework.",
    typical_continuing_education: "Leadership, HR basics, and inventory management.",
    specialty_certifications: ["Salon management certificates", "Retail leadership"],
    career_advancement: "Salon owner, multi-location operator, or brand educator.",
    icon: "Users",
  },
  {
    name: "Salon Owner",
    category: "business",
    description: "Owns or partners in a salon — P&L, hiring, marketing, and compliance.",
    median_annual_salary: 49260,
    salary_range_low: 35000,
    salary_range_high: 120000,
    bls_source_link: `${BLS}oes119179.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_cosmetology_or_barber_license", "business_registration"],
    required_education: "Active license plus business planning; income varies with ownership model.",
    typical_continuing_education: "Business law, tax, and leadership CE.",
    specialty_certifications: ["Small business management", "Salon suite franchise training"],
    career_advancement: "Multi-location owner, product line, or education company.",
    icon: "Building2",
  },
  {
    name: "Platform Artist",
    category: "hair",
    description: "Travels for brand education, stage demos, and content creation.",
    median_annual_salary: 45000,
    salary_range_low: 32000,
    salary_range_high: 95000,
    bls_source_link: `${BLS}oes395012.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_cosmetology_or_barber_license"],
    required_education: "License plus portfolio; brand contract training.",
    typical_continuing_education: "Teaching methodology and stage presentation.",
    specialty_certifications: ["Brand ambassador programs", "Stage cut / color certs"],
    career_advancement: "Creative director, product development consultant.",
    icon: "Mic",
  },
  {
    name: "Beauty Educator",
    category: "business",
    description: "Teaches in cosmetology schools or delivers CE to licensed professionals.",
    median_annual_salary: 42000,
    salary_range_low: 32000,
    salary_range_high: 68000,
    bls_source_link: `${BLS}oes259032.htm`,
    salary_data_year: 2023,
    required_license_types: ["instructor_license_where_required", "active_practitioner_license"],
    required_education: "License plus instructor training (often 500+ additional hours).",
    typical_continuing_education: "Adult learning theory; curriculum updates.",
    specialty_certifications: ["CIDESCO-adjacent CE", "State instructor license"],
    career_advancement: "School director, platform artist, or curriculum author.",
    icon: "GraduationCap",
  },
  {
    name: "Celebrity / Session Stylist",
    category: "hair",
    description: "On-set, tour, and red-carpet styling for talent and production.",
    median_annual_salary: 52000,
    salary_range_low: 35000,
    salary_range_high: 150000,
    bls_source_link: `${BLS}oes395012.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_cosmetology_license"],
    required_education: "License plus union / production networking; highly variable income.",
    typical_continuing_education: "Session styling and wig work workshops.",
    specialty_certifications: ["Extension mastery", "Period styling"],
    career_advancement: "Creative director, product collaborator, or agency representation.",
    icon: "Star",
  },
  {
    name: "Mobile Beauty Professional",
    category: "business",
    description: "Brings services to clients' homes, events, or corporate settings.",
    median_annual_salary: 36000,
    salary_range_low: 24000,
    salary_range_high: 65000,
    bls_source_link: `${BLS}oes395012.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_license_in_service_category"],
    required_education: "License plus mobile business permits and liability insurance.",
    typical_continuing_education: "Sanitation for mobile setups.",
    specialty_certifications: ["Bridal styling", "On-location color"],
    career_advancement: "Suite owner, agency lead, or product educator.",
    icon: "Car",
  },
  {
    name: "Suite / Studio Owner",
    category: "business",
    description: "Rents or owns a suite within a collective; self-directed clientele.",
    median_annual_salary: 45000,
    salary_range_low: 30000,
    salary_range_high: 95000,
    bls_source_link: `${BLS}oes395012.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_license", "business_registration"],
    required_education: "License plus lease economics and tax planning.",
    typical_continuing_education: "Business CE and marketing.",
    specialty_certifications: ["Suite franchise onboarding"],
    career_advancement: "Multi-suite investor or educator.",
    icon: "DoorOpen",
  },
  {
    name: "Med Spa Technician",
    category: "skin",
    description: "Device-backed treatments in medical-spa settings under appropriate supervision.",
    median_annual_salary: 46000,
    salary_range_low: 34000,
    salary_range_high: 72000,
    bls_source_link: `${BLS}oes395094.htm`,
    salary_data_year: 2023,
    required_license_types: ["esthetics_license", "medical_director_oversight"],
    required_education: "Esthetics license plus device manufacturer training.",
    typical_continuing_education: "Laser / RF safety refreshers.",
    specialty_certifications: ["Laser hair reduction", "Microneedling (where allowed)"],
    career_advancement: "Lead technician, clinic manager, or trainer.",
    icon: "Stethoscope",
  },
  {
    name: "Laser Technician",
    category: "skin",
    description: "Performs laser and light-based services where state rules allow under MD oversight.",
    median_annual_salary: 47000,
    salary_range_low: 35000,
    salary_range_high: 75000,
    bls_source_link: `${BLS}oes395094.htm`,
    salary_data_year: 2023,
    required_license_types: ["esthetics_or_rn_scope", "laser_certification"],
    required_education: "Esthetics or nursing pathway plus laser safety course.",
    typical_continuing_education: "Device-specific annual training.",
    specialty_certifications: ["Laser physics & safety", "IPL protocols"],
    career_advancement: "Med spa lead or aesthetic nurse pathway (RN).",
    icon: "Zap",
  },
  {
    name: "Wedding & Event Stylist",
    category: "hair",
    description: "Bridal parties, editorial, and on-location event styling.",
    median_annual_salary: 40000,
    salary_range_low: 28000,
    salary_range_high: 78000,
    bls_source_link: `${BLS}oes395012.htm`,
    salary_data_year: 2023,
    required_license_types: ["state_cosmetology_license"],
    required_education: "License plus portfolio and contract templates.",
    typical_continuing_education: "Bridal business and trial planning.",
    specialty_certifications: ["Airbrush makeup (if dual-licensed)", "Extension styling"],
    career_advancement: "Celebrity session work or agency ownership.",
    icon: "Heart",
  },
  {
    name: "Nail Art Specialist",
    category: "nails",
    description: "Competition-level art, structure, and social content monetization.",
    median_annual_salary: 35000,
    salary_range_low: 24000,
    salary_range_high: 62000,
    bls_source_link: `${BLS}oes395092.htm`,
    salary_data_year: 2023,
    required_license_types: ["nail_technology_license"],
    required_education: "Nail program plus art / structure CE.",
    typical_continuing_education: "E-file and chemistry safety.",
    specialty_certifications: ["Competition nail art", "3D sculpting"],
    career_advancement: "Educator, brand ambassador, or suite owner.",
    icon: "Brush",
  },
  {
    name: "Lash Artist",
    category: "lashes",
    description: "Classic and volume lash extensions within state scope.",
    median_annual_salary: 38000,
    salary_range_low: 26000,
    salary_range_high: 65000,
    bls_source_link: `${BLS}oes395094.htm`,
    salary_data_year: 2023,
    required_license_types: ["esthetics_or_cosmetology_license", "lash_certification"],
    required_education: "Base license plus certified lash training (varies by state).",
    typical_continuing_education: "Isolation safety and adhesive chemistry.",
    specialty_certifications: ["Volume / mega-volume", "Lash lift & tint"],
    career_advancement: "Suite owner or lash educator.",
    icon: "Eye",
  },
  {
    name: "Brow & Lamination Specialist",
    category: "lashes",
    description: "Brow shaping, tinting, lamination, and henna where permitted.",
    median_annual_salary: 36000,
    salary_range_low: 25000,
    salary_range_high: 58000,
    bls_source_link: `${BLS}oes395094.htm`,
    salary_data_year: 2023,
    required_license_types: ["esthetics_or_cosmetology_license"],
    required_education: "License plus brow / lamination certification.",
    typical_continuing_education: "Patch testing and contraindications.",
    specialty_certifications: ["Brow lamination", "Microblading PMU (separate regulation)"],
    career_advancement: "Full-face aesthetic specialist or educator.",
    icon: "ScanFace",
  },
  {
    name: "Personal Trainer",
    category: "massage",
    description: "Fitness coaching — often complementary to beauty/wellness careers.",
    median_annual_salary: 46480,
    salary_range_low: 28000,
    salary_range_high: 78000,
    bls_source_link: `${BLS}oes399031.htm`,
    salary_data_year: 2023,
    required_license_types: ["nationally_accredited_certification"],
    required_education: "CPT certification (ACE, NASM, ISSA, etc.).",
    typical_continuing_education: "CPR/AED; specialty populations.",
    specialty_certifications: ["Corrective exercise", "Nutrition coaching (non-RD scope)"],
    career_advancement: "Studio owner, online coach, or wellness brand partner.",
    icon: "Dumbbell",
  },
  {
    name: "Multi-Location Owner",
    category: "business",
    description: "Operates two or more salons, suites, or franchise units.",
    median_annual_salary: 72000,
    salary_range_low: 45000,
    salary_range_high: 180000,
    bls_source_link: `${BLS}oes119179.htm`,
    salary_data_year: 2023,
    required_license_types: ["business_entities", "licensed_managers_on_site"],
    required_education: "Prior ownership experience plus finance and HR systems.",
    typical_continuing_education: "Multi-unit operations and compliance.",
    specialty_certifications: ["Franchise operations", "MBA / business courses (optional)"],
    career_advancement: "Regional brand, product distribution, or private equity exit.",
    icon: "Network",
  },
  {
    name: "Brand Ambassador",
    category: "business",
    description: "Represents product lines through content, classes, and retail partnerships.",
    median_annual_salary: 42000,
    salary_range_low: 30000,
    salary_range_high: 85000,
    bls_source_link: `${BLS}oes419091.htm`,
    salary_data_year: 2023,
    required_license_types: ["active_license_in_category"],
    required_education: "License plus brand contract and social compliance training.",
    typical_continuing_education: "Product chemistry and FTC disclosure rules.",
    specialty_certifications: ["Brand-specific academies"],
    career_advancement: "Platform artist or product development role.",
    icon: "Megaphone",
  },
  {
    name: "Barber Shop Owner",
    category: "business",
    description: "Owns a barbershop — chair rental, culture, and service menu.",
    median_annual_salary: 52000,
    salary_range_low: 38000,
    salary_range_high: 110000,
    bls_source_link: `${BLS}oes119179.htm`,
    salary_data_year: 2023,
    required_license_types: ["barber_license", "business_registration"],
    required_education: "Barber license plus shop operations experience.",
    typical_continuing_education: "Shop safety audits and tax planning.",
    specialty_certifications: ["Barbershop management workshops"],
    career_advancement: "Multi-shop owner or education brand.",
    icon: "Store",
  },
  {
    name: "Balayage Expert",
    category: "hair",
    description: "Specializes in hand-painted lightening and lived-in color.",
    median_annual_salary: 45000,
    salary_range_low: 32000,
    salary_range_high: 85000,
    bls_source_link: `${BLS}oes395012.htm`,
    salary_data_year: 2023,
    required_license_types: ["cosmetology_license"],
    required_education: "License plus advanced lightening CE.",
    typical_continuing_education: "Toning and bond-building protocols.",
    specialty_certifications: ["Balayage / babylight academies"],
    career_advancement: "Educator, platform artist, or celebrity stylist.",
    icon: "Sun",
  },
  {
    name: "Medical Aesthetics Provider",
    category: "skin",
    description: "RN or NP pathway for injectables and advanced med-aesthetics (separate licensure).",
    median_annual_salary: 77000,
    salary_range_low: 55000,
    salary_range_high: 120000,
    bls_source_link: `${BLS}oes291141.htm`,
    salary_data_year: 2023,
    required_license_types: ["registered_nurse_or_np", "medical_director"],
    required_education: "Nursing degree plus aesthetic nursing CE.",
    typical_continuing_education: "Injection anatomy and complication management.",
    specialty_certifications: ["Aesthetic nursing certifications"],
    career_advancement: "Clinic director or training institute lead.",
    icon: "Syringe",
  },
  {
    name: "Nail Educator",
    category: "nails",
    description: "Teaches nail technology in schools or advanced CE classes.",
    median_annual_salary: 40000,
    salary_range_low: 32000,
    salary_range_high: 58000,
    bls_source_link: `${BLS}oes259032.htm`,
    salary_data_year: 2023,
    required_license_types: ["nail_license", "instructor_license_where_required"],
    required_education: "Nail license plus instructor credentials.",
    typical_continuing_education: "Teaching methodology.",
    specialty_certifications: ["Competition judging", "Product chemistry"],
    career_advancement: "School director or social educator.",
    icon: "BookOpen",
  },
  {
    name: "Mobile Barber / Studio Owner",
    category: "hair",
    description: "Barber with owned studio or mobile unit — common career-change outcome.",
    median_annual_salary: 48000,
    salary_range_low: 32000,
    salary_range_high: 90000,
    bls_source_link: `${BLS}oes395011.htm`,
    salary_data_year: 2023,
    required_license_types: ["barber_license"],
    required_education: "Barber school plus business setup.",
    typical_continuing_education: "Mobile sanitation and booking systems.",
    specialty_certifications: ["Shop ownership workshops"],
    career_advancement: "Multi-chair shop owner or educator.",
    icon: "Truck",
  },
];

const roleIdList = Object.values(ROLE_IDS);

export const SEED_ROLES_WITH_IDS = SEED_ROLES.map((r, i) => ({
  ...r,
  id: roleIdList[i] ?? `r1999999-0000-4000-8000-${String(i).padStart(12, "0")}`,
}));

export const SEED_PATHS: SeedPath[] = [
  {
    id: PATH_IDS.hsToSalonOwner,
    starting_point: "high_school",
    end_role: "salon_owner",
    name: "High school → salon owner",
    description:
      "Cosmetology school, licensure, floor experience, management, and ownership — multiple valid branches along the way.",
    estimated_total_years: 7,
    estimated_total_investment: 45000,
    order_index: 1,
    milestones: [
      m(1, "Explore cosmetology programs", "Research accredited schools and state hour requirements.", 3, 500, ["research_schools"], ["Shortlist programs"]),
      m(2, "Complete cosmetology school", "Clock hours, mock boards, and practical exams.", 12, 18000, ["state_cosmetology_program"], ["Graduate eligible for board"]),
      m(3, "Pass state board exams", "Written + practical per your state vendor.", 2, 400, ["state_board_exams"], ["Licensed cosmetologist"], ROLE_IDS.cosmetologist),
      m(4, "Associate / commission chair", "Build speed, rebooking, and retail attachment.", 24, 2000, ["employment"], ["Consistent book"], ROLE_IDS.cosmetologist),
      m(5, "Lead stylist or team lead", "Mentor juniors and own advanced tickets.", 24, 3000, ["continuing_education"], ["Senior title"], ROLE_IDS.colorSpecialist),
      m(6, "Salon manager track", "Scheduling, P&L exposure, hiring.", 18, 2500, ["management_ce"], ["Manager role"], ROLE_IDS.salonManager),
      m(7, "Open or buy a salon", "Lease, build-out, insurance, marketing.", 12, 20000, ["business_license", "capital"], ["Owner"], ROLE_IDS.salonOwner),
    ],
  },
  {
    id: PATH_IDS.careerChangeBarber,
    starting_point: "career_change",
    end_role: "salon_owner",
    name: "Career change → barber → studio owner",
    description: "Pivot into barbering, build a book, then mobile or studio ownership.",
    estimated_total_years: 5,
    estimated_total_investment: 32000,
    order_index: 2,
    milestones: [
      m(1, "Barber school enrollment", "Verify state barber vs cosmetology path.", 1, 300, ["school_application"], ["Accepted"]),
      m(2, "Complete barber program", "Fades, sanitation, state law.", 10, 14000, ["barber_program"], ["Graduate"], ROLE_IDS.barber),
      m(3, "Licensed barber on floor", "Shop employment or rental.", 18, 1500, ["state_license"], ["Full book"], ROLE_IDS.barber),
      m(4, "Mobile barber clientele", "Equipment + liability coverage.", 12, 4000, ["business_registration"], ["Mobile income"], ROLE_IDS.mobilePro),
      m(5, "Studio / shop ownership", "Chair rental model or owned shop.", 18, 12000, ["capital", "lease"], ["Owner"], ROLE_IDS.studioBarber),
    ],
  },
  {
    id: PATH_IDS.careerChangeMedspa,
    starting_point: "career_change",
    end_role: "educator",
    name: "Career change → esthetics → med spa",
    description: "Esthetics license, device training, med-spa employment — clinical lane optional later.",
    estimated_total_years: 4,
    estimated_total_investment: 22000,
    order_index: 3,
    milestones: [
      m(1, "Esthetics school", "Skin science and sanitation foundations.", 8, 12000, ["esthetics_program"], ["Graduate"]),
      m(2, "State esthetics license", "Board exams per jurisdiction.", 2, 350, ["state_board"], ["Licensed"], ROLE_IDS.esthetician),
      m(3, "Spa employment", "Build facial series and retail.", 12, 1000, ["employment"], ["Stable clientele"], ROLE_IDS.esthetician),
      m(4, "Laser / device certification", "Manufacturer-led training.", 3, 4500, ["device_cert"], ["Med spa eligible"], ROLE_IDS.laserTech),
      m(5, "Med spa technician", "Work under medical director.", 18, 1500, ["medical_oversight"], ["Clinical track"], ROLE_IDS.medSpaTech),
    ],
  },
  {
    id: PATH_IDS.licensedToEducator,
    starting_point: "currently_licensed",
    end_role: "educator",
    name: "Licensed pro → educator → platform artist",
    description: "Leverage existing license toward teaching and brand partnerships.",
    estimated_total_years: 4,
    estimated_total_investment: 12000,
    order_index: 4,
    milestones: [
      m(1, "Document mastery portfolio", "Before/afters, timing, testimonials.", 6, 500, ["portfolio"], ["Teaching-ready work"]),
      m(2, "Continuing education depth", "Advanced CE in your specialty.", 12, 3500, ["continuing_education_hours"], ["Specialist positioning"], ROLE_IDS.colorSpecialist),
      m(3, "Instructor license (if required)", "Additional hours per state.", 6, 6000, ["instructor_license"], ["School-eligible"], ROLE_IDS.educator),
      m(4, "School or freelance educator", "Paid classes and content.", 18, 2000, ["teaching_contract"], ["Educator income"], ROLE_IDS.educator),
      m(5, "Platform artist", "Brand stages and travel.", 24, 1000, ["brand_contract"], ["Platform career"], ROLE_IDS.platformArtist),
    ],
  },
  {
    id: PATH_IDS.licensedToMultiOwner,
    starting_point: "experienced_pro",
    end_role: "salon_owner",
    name: "Experienced pro → manager → multi-location owner",
    description: "Business coursework and unit economics for scaling beyond one site.",
    estimated_total_years: 5,
    estimated_total_investment: 55000,
    order_index: 5,
    milestones: [
      m(1, "Salon management role", "KPIs, labor law basics.", 12, 1500, ["management"], ["Manager title"], ROLE_IDS.salonManager),
      m(2, "First salon ownership", "Single unit P&L ownership.", 24, 35000, ["capital", "lease"], ["Owner"], ROLE_IDS.salonOwner),
      m(3, "Systems & hiring playbook", "SOPs, training, retention.", 12, 5000, ["hr_systems"], ["Scalable ops"]),
      m(4, "Second location or acquisition", "Financing and duplicate leadership.", 18, 12000, ["financing"], ["Multi-unit"], ROLE_IDS.multiLocationOwner),
    ],
  },
  {
    id: PATH_IDS.schoolToColorEducator,
    starting_point: "high_school",
    end_role: "educator",
    name: "Cosmetology school → color specialist → educator",
    description: "Hair color depth, balayage expertise, then teaching credentials.",
    estimated_total_years: 6,
    estimated_total_investment: 28000,
    order_index: 6,
    milestones: [
      m(1, "Cosmetology program", "Core license pathway.", 12, 17000, ["cosmetology_program"], ["Licensed"], ROLE_IDS.cosmetologist),
      m(2, "Color specialist floor time", "Formulation and corrections.", 18, 2500, ["employment"], ["Color book"], ROLE_IDS.colorSpecialist),
      m(3, "Balayage mastery", "Advanced lightening CE.", 12, 4000, ["advanced_ce"], ["Premium services"], ROLE_IDS.balayageExpert),
      m(4, "Assistant educator → lead educator", "Classroom hours.", 18, 4500, ["instructor_license"], ["Teaching"], ROLE_IDS.educator),
    ],
  },
  {
    id: PATH_IDS.estheticsToLaser,
    starting_point: "currently_licensed",
    end_role: "educator",
    name: "Esthetics → laser certification → med spa lead",
    description: "Device credentials and clinical environment experience.",
    estimated_total_years: 3,
    estimated_total_investment: 15000,
    order_index: 7,
    milestones: [
      m(1, "Active esthetics license", "Maintain renewal CE.", 1, 200, ["license_renewal"], ["Active"]),
      m(2, "Laser safety certification", "Physics and protocols.", 2, 5000, ["laser_cert"], ["Device-ready"], ROLE_IDS.laserTech),
      m(3, "Med spa employment", "Series-based revenue.", 18, 1000, ["employment"], ["Clinical experience"], ROLE_IDS.medSpaTech),
      m(4, "Lead technician or trainer", "Protocol ownership.", 12, 3000, ["leadership"], ["Lead role"], ROLE_IDS.medSpaTech),
    ],
  },
  {
    id: PATH_IDS.nailToInfluencer,
    starting_point: "career_change",
    end_role: "platform_artist",
    name: "Nail tech → nail art specialist → educator / influencer",
    description: "Structure, art, content, and brand partnerships.",
    estimated_total_years: 4,
    estimated_total_investment: 14000,
    order_index: 8,
    milestones: [
      m(1, "Nail technology school", "License pathway.", 6, 8000, ["nail_program"], ["Licensed"], ROLE_IDS.nailTech),
      m(2, "Structure + e-file mastery", "Speed with safe chemistry.", 12, 1500, ["e_file_cert"], ["Full book"], ROLE_IDS.nailTech),
      m(3, "Nail art specialization", "Competition-level skills.", 12, 2500, ["art_ce"], ["Premium sets"], ROLE_IDS.nailArtSpecialist),
      m(4, "Content + brand deals", "FTC-compliant partnerships.", 18, 2000, ["social_compliance"], ["Educator / ambassador"], ROLE_IDS.nailEducator),
    ],
  },
  {
    id: PATH_IDS.cosmoToCelebrity,
    starting_point: "experienced_pro",
    end_role: "celebrity_stylist",
    name: "Cosmetology → wedding focus → celebrity stylist",
    description: "Event portfolio, agency networking, session work.",
    estimated_total_years: 8,
    estimated_total_investment: 20000,
    order_index: 9,
    milestones: [
      m(1, "Licensed cosmetologist", "Active license.", 1, 200, ["license"], ["Active"], ROLE_IDS.cosmetologist),
      m(2, "Wedding & event portfolio", "Trials, contracts, travel kits.", 24, 5000, ["portfolio"], ["Event book"], ROLE_IDS.weddingStylist),
      m(3, "Agency / representation", "Session and tour opportunities.", 24, 8000, ["networking"], ["Session work"], ROLE_IDS.celebrityStylist),
      m(4, "Celebrity stylist positioning", "Union rates where applicable.", 36, 7000, ["contracts"], ["Top-tier clients"], ROLE_IDS.celebrityStylist),
    ],
  },
  {
    id: PATH_IDS.massageSpecialty,
    starting_point: "career_change",
    end_role: "salon_owner",
    name: "Massage school → LMT → specialty → private practice",
    description: "Clinical or sports specialty with optional solo practice.",
    estimated_total_years: 4,
    estimated_total_investment: 18000,
    order_index: 10,
    milestones: [
      m(1, "Massage therapy program", "Accredited hours.", 9, 12000, ["massage_program"], ["Graduate"]),
      m(2, "State massage license", "MBLEx or state exam.", 2, 400, ["state_license"], ["LMT"], ROLE_IDS.massageTherapist),
      m(3, "Spa or clinical employment", "Build modalities.", 12, 800, ["employment"], ["Specialty focus"]),
      m(4, "Sports or medical massage CE", "Advanced certification.", 6, 3500, ["specialty_ce"], ["Higher ticket"], ROLE_IDS.massageTherapist),
      m(5, "Private practice / suite", "Business setup.", 12, 2500, ["business_license"], ["Owner-practitioner"], ROLE_IDS.suiteOwner),
    ],
  },
];

function m(
  order: number,
  name: string,
  description: string,
  months: number,
  cost: number,
  requirements: string[],
  outcomes: string[],
  roleId?: string,
): SeedMilestone {
  return {
    milestone_order: order,
    name,
    description,
    estimated_duration_months: months,
    estimated_cost: cost,
    requirements,
    typical_outcomes: outcomes,
    role_id: roleId,
  };
}

export const TOTAL_SEED_ROLES = SEED_ROLES_WITH_IDS.length;
export const TOTAL_SEED_PATHS = SEED_PATHS.length;
