import type { BeautyBodyService, BeautyBodyZone, BodyZoneId } from "@/types/affirmations";

export const SEED_BODY_ZONES: BeautyBodyZone[] = [
  { id: "head", name: "Head & scalp", description: "Scalp treatments, growth care, and protective styling foundations.", icon_svg: null },
  { id: "face", name: "Face", description: "Skin, makeup, brows, and facial hair framing.", icon_svg: null },
  { id: "hair", name: "Hair", description: "Cuts, color, styling, and texture services.", icon_svg: null },
  { id: "neck", name: "Neck & décolleté", description: "Neckline care, waxing, and finishing details.", icon_svg: null },
  { id: "hands", name: "Hands", description: "Manicures, nail art, and hand treatments.", icon_svg: null },
  { id: "body", name: "Body", description: "Massage, body treatments, waxing, and tanning.", icon_svg: null },
  { id: "feet", name: "Feet", description: "Pedicures, foot care, and reflexology.", icon_svg: null },
  { id: "nails", name: "Nails", description: "Full nail services across fingers and toes.", icon_svg: null },
];

function sid(n: number): string {
  return `s${String(n).padStart(7, "0")}-0002-4002-8002-${String(n).padStart(12, "0")}`;
}

type S = Omit<BeautyBodyService, "id"> & { id?: string };

const SERVICE_ROWS: (S & { zone_id: BodyZoneId })[] = [
  { zone_id: "head", service_name: "Scalp treatment", description: "Deep cleanse and treatment for scalp health.", category: "hair_treatments", average_duration_minutes: 45, average_price_range: "$45–$85", finding_pros_filter: { serviceCategories: ["hair_treatments"], specialties: ["hair"], searchTerms: ["scalp"] }, what_to_expect: "Analysis, exfoliation, mask, and massage.", prep_tips: "Arrive with dry hair unless instructed otherwise.", aftercare: "Avoid heavy oils 24h if a detox treatment was used." },
  { zone_id: "head", service_name: "Keratin smoothing", description: "Smoothing treatment to reduce frizz.", category: "hair_treatments", average_duration_minutes: 180, average_price_range: "$250–$450", finding_pros_filter: { serviceCategories: ["hair_treatments"], specialties: ["hair"] }, what_to_expect: "Long appointment with ventilation; results last months.", prep_tips: "Clarifying wash often required; discuss prior color.", aftercare: "Wait 72h before washing; sulfate-free home care." },
  { zone_id: "head", service_name: "Scalp massage", description: "Relaxation-focused scalp work.", category: "massage", average_duration_minutes: 20, average_price_range: "$25–$55", finding_pros_filter: { serviceCategories: ["massage"], specialties: ["hair"] }, what_to_expect: "Seated massage, often add-on to cut or color.", prep_tips: "Mention headaches or tension areas.", aftercare: "Hydrate; gentle brushing." },
  { zone_id: "head", service_name: "Protective braid install", description: "Braids that protect natural hair.", category: "hair_styling", average_duration_minutes: 240, average_price_range: "$150–$350", finding_pros_filter: { serviceCategories: ["hair_styling"], specialties: ["hair"], searchTerms: ["braid"] }, what_to_expect: "Long session; tension should stay comfortable.", prep_tips: "Come with washed, stretched hair if requested.", aftercare: "Moisturize scalp; avoid excessive tension." },
  { zone_id: "face", service_name: "Classic facial", description: "Cleanse, exfoliate, extract, mask, moisturize.", category: "facials", average_duration_minutes: 60, average_price_range: "$85–$150", finding_pros_filter: { serviceCategories: ["facials", "skincare"], specialties: ["skin"] }, what_to_expect: "Customized steps for your skin type.", prep_tips: "Skip retinoids 48h before if advised.", aftercare: "SPF daily; gentle products 24h." },
  { zone_id: "face", service_name: "Dermaplaning", description: "Exfoliation and peach-fuzz removal.", category: "facials", average_duration_minutes: 45, average_price_range: "$75–$130", finding_pros_filter: { serviceCategories: ["facials"], specialties: ["skin"] }, what_to_expect: "Blade exfoliation; smooth finish for makeup.", prep_tips: "Disclose acne or active breakouts.", aftercare: "Avoid sun and harsh acids 48h." },
  { zone_id: "face", service_name: "Chemical peel", description: "Controlled exfoliation by skin depth.", category: "facials", average_duration_minutes: 30, average_price_range: "$100–$250", finding_pros_filter: { serviceCategories: ["facials", "med_spa"], specialties: ["skin", "medspa"] }, what_to_expect: "Tingling; peeling days after.", prep_tips: "Pre-peel regimen may be required.", aftercare: "Strict SPF; follow post-care sheet." },
  { zone_id: "face", service_name: "Bridal makeup", description: "Event-ready makeup application.", category: "makeup_bridal", average_duration_minutes: 90, average_price_range: "$150–$350", finding_pros_filter: { serviceCategories: ["makeup_bridal", "makeup"], specialties: ["makeup"] }, what_to_expect: "Trial often booked separately.", prep_tips: "Bring inspiration photos.", aftercare: "Setting spray; blotting only if needed." },
  { zone_id: "face", service_name: "Brow lamination", description: "Brush-up brow shape that lasts weeks.", category: "brows", average_duration_minutes: 45, average_price_range: "$65–$110", finding_pros_filter: { serviceCategories: ["brows"], specialties: ["brow", "lash"] }, what_to_expect: "Lift, set, and tint optional.", prep_tips: "Avoid retinoids on brows beforehand.", aftercare: "Keep dry 24h; no oil on brows." },
  { zone_id: "face", service_name: "Lash lift", description: "Natural lash curl without extensions.", category: "lashes", average_duration_minutes: 60, average_price_range: "$75–$125", finding_pros_filter: { serviceCategories: ["lashes"], specialties: ["lash"] }, what_to_expect: "Patch test if tint included.", prep_tips: "Remove eye makeup.", aftercare: "No water/steam 24h." },
  { zone_id: "hair", service_name: "Haircut", description: "Cut and finish for your hair type.", category: "hair_cut", average_duration_minutes: 60, average_price_range: "$45–$120", finding_pros_filter: { serviceCategories: ["hair_cut"], specialties: ["hair"] }, what_to_expect: "Consultation, cut, blowdry or diffuse.", prep_tips: "Bring reference photos.", aftercare: "Style as recommended; book maintenance." },
  { zone_id: "hair", service_name: "Balayage", description: "Hand-painted lightening for dimension.", category: "hair_color", average_duration_minutes: 180, average_price_range: "$200–$400", finding_pros_filter: { serviceCategories: ["hair_color"], specialties: ["hair"], searchTerms: ["balayage", "color"] }, what_to_expect: "Multi-hour process; toner often included.", prep_tips: "Wash 24h before unless told otherwise.", aftercare: "Bond treatments; color-safe shampoo." },
  { zone_id: "hair", service_name: "Full color", description: "All-over color application.", category: "hair_color", average_duration_minutes: 120, average_price_range: "$120–$250", finding_pros_filter: { serviceCategories: ["hair_color"], specialties: ["hair"] }, what_to_expect: "Roots to ends or regrowth focus.", prep_tips: "Share allergy history.", aftercare: "Wait 48h before clarifying washes." },
  { zone_id: "hair", service_name: "Blowout", description: "Wash and smooth styling.", category: "hair_styling", average_duration_minutes: 45, average_price_range: "$40–$85", finding_pros_filter: { serviceCategories: ["hair_styling"], specialties: ["hair"] }, what_to_expect: "Volume or sleek finish.", prep_tips: "Come with clean or day-old hair per policy.", aftercare: "Silk pillowcase helps longevity." },
  { zone_id: "hair", service_name: "Tape-in extensions", description: "Semi-permanent length and volume.", category: "hair_extensions", average_duration_minutes: 150, average_price_range: "$300–$600+", finding_pros_filter: { serviceCategories: ["hair_extensions"], specialties: ["hair"], searchTerms: ["extension"] }, what_to_expect: "Install and blend cut.", prep_tips: "Color match consult first.", aftercare: "Brush gently; avoid oily roots." },
  { zone_id: "hair", service_name: "Highlights", description: "Foil or babylight dimension.", category: "hair_color", average_duration_minutes: 150, average_price_range: "$150–$320", finding_pros_filter: { serviceCategories: ["hair_color"], specialties: ["hair"] }, what_to_expect: "Partial or full head options.", prep_tips: "Bring inspiration; discuss maintenance.", aftercare: "Purple shampoo as directed." },
  { zone_id: "hair", service_name: "Silk press", description: "Smoothing on natural texture.", category: "hair_styling", average_duration_minutes: 90, average_price_range: "$65–$130", finding_pros_filter: { serviceCategories: ["hair_styling"], specialties: ["hair"] }, what_to_expect: "Heat styling with heat protectant.", prep_tips: "Clarifying wash may be required.", aftercare: "Wrap hair at night; limit moisture until redo." },
  { zone_id: "hair", service_name: "Barber fade", description: "Tapered clipper work and line-up.", category: "barbering", average_duration_minutes: 45, average_price_range: "$35–$65", finding_pros_filter: { serviceCategories: ["barbering"], specialties: ["barber"] }, what_to_expect: "Consultation on guard lengths.", prep_tips: "Know your last fade height.", aftercare: "Edge upkeep between visits." },
  { zone_id: "neck", service_name: "Neckline cleanup", description: "Detail trim for nape and sides.", category: "barbering", average_duration_minutes: 15, average_price_range: "$15–$35", finding_pros_filter: { serviceCategories: ["barbering"], specialties: ["barber", "hair"] }, what_to_expect: "Quick add-on or standalone.", prep_tips: "Specify beard overlap if any.", aftercare: "Soothe with alcohol-free aftershave." },
  { zone_id: "neck", service_name: "Décolleté facial", description: "Care for chest and neck skin.", category: "facials", average_duration_minutes: 30, average_price_range: "$50–$95", finding_pros_filter: { serviceCategories: ["facials", "skincare"], specialties: ["skin"] }, what_to_expect: "Often paired with facial.", prep_tips: "Note sun damage or sensitivity.", aftercare: "SPF on exposed area." },
  { zone_id: "neck", service_name: "Neck wax", description: "Hair removal for neckline.", category: "waxing", average_duration_minutes: 15, average_price_range: "$20–$45", finding_pros_filter: { serviceCategories: ["waxing"], specialties: ["skin", "hair"] }, what_to_expect: "Quick strip or hard wax.", prep_tips: "Hair length ~¼ inch.", aftercare: "Avoid sweat 24h." },
  { zone_id: "hands", service_name: "Gel manicure", description: "Long-wear polish with cure.", category: "nails_manicure", average_duration_minutes: 60, average_price_range: "$40–$75", finding_pros_filter: { serviceCategories: ["nails_manicure", "nails"], specialties: ["nail"] }, what_to_expect: "Prep, gel application, cure.", prep_tips: "No heavy hand lotion before.", aftercare: "Cuticle oil daily; avoid picking." },
  { zone_id: "hands", service_name: "Classic manicure", description: "Shape, cuticle care, polish.", category: "nails_manicure", average_duration_minutes: 45, average_price_range: "$25–$50", finding_pros_filter: { serviceCategories: ["nails_manicure"], specialties: ["nail"] }, what_to_expect: "Soak, file, polish.", prep_tips: "Remove old polish if possible.", aftercare: "Gloves for cleaning 24h." },
  { zone_id: "hands", service_name: "Acrylic full set", description: "Sculpted length and shape.", category: "nails", average_duration_minutes: 90, average_price_range: "$55–$95", finding_pros_filter: { serviceCategories: ["nails"], specialties: ["nail"] }, what_to_expect: "Fill needed every 2–3 weeks.", prep_tips: "Choose shape in advance.", aftercare: "Report lifting early." },
  { zone_id: "hands", service_name: "Nail art", description: "Custom design on natural or enhanced nails.", category: "nails", average_duration_minutes: 30, average_price_range: "$15–$60+", finding_pros_filter: { serviceCategories: ["nails"], specialties: ["nail"], searchTerms: ["nail art"] }, what_to_expect: "Priced per nail or set.", prep_tips: "Bring reference images.", aftercare: "Top coat refresh as needed." },
  { zone_id: "hands", service_name: "Paraffin hand treatment", description: "Warm wax hydration for hands.", category: "nails", average_duration_minutes: 20, average_price_range: "$15–$35", finding_pros_filter: { serviceCategories: ["nails"], specialties: ["nail", "skin"] }, what_to_expect: "Add-on warmth and softness.", prep_tips: "Disclose circulation issues.", aftercare: "Avoid hot water immediately." },
  { zone_id: "body", service_name: "Swedish massage", description: "Relaxation-focused full body work.", category: "massage", average_duration_minutes: 60, average_price_range: "$80–$140", finding_pros_filter: { serviceCategories: ["massage"], specialties: ["massage"] }, what_to_expect: "Draping maintained; pressure adjustable.", prep_tips: "Hydrate; arrive early.", aftercare: "Water and light movement." },
  { zone_id: "body", service_name: "Deep tissue massage", description: "Focused pressure for tension.", category: "massage", average_duration_minutes: 60, average_price_range: "$95–$160", finding_pros_filter: { serviceCategories: ["massage"], specialties: ["massage"] }, what_to_expect: "May be intense; speak up on pressure.", prep_tips: "Avoid heavy meals before.", aftercare: "Soreness 24h can be normal." },
  { zone_id: "body", service_name: "Body scrub", description: "Exfoliation for smooth skin.", category: "skincare", average_duration_minutes: 45, average_price_range: "$70–$120", finding_pros_filter: { serviceCategories: ["skincare"], specialties: ["skin"] }, what_to_expect: "Shower before or after per spa.", prep_tips: "Shave 24h before if sensitive.", aftercare: "Moisturize; SPF if exposed." },
  { zone_id: "body", service_name: "Brazilian wax", description: "Full bikini hair removal.", category: "waxing", average_duration_minutes: 45, average_price_range: "$55–$95", finding_pros_filter: { serviceCategories: ["waxing"], specialties: ["skin"] }, what_to_expect: "Professional draping and technique.", prep_tips: "Hair ~¼ inch; avoid retinoids.", aftercare: "Loose clothing; no heat 24h." },
  { zone_id: "body", service_name: "Spray tan", description: "Sunless color application.", category: "other", average_duration_minutes: 30, average_price_range: "$35–$75", finding_pros_filter: { serviceCategories: ["other"], searchTerms: ["spray tan"] }, what_to_expect: "Stand or booth; develops over hours.", prep_tips: "Exfoliate; no lotion day-of.", aftercare: "Avoid water 8h; moisturize after." },
  { zone_id: "body", service_name: "Lymphatic drainage", description: "Gentle rhythm for fluid movement.", category: "massage", average_duration_minutes: 60, average_price_range: "$120–$200", finding_pros_filter: { serviceCategories: ["massage", "med_spa"], specialties: ["medspa", "massage"] }, what_to_expect: "Light pressure; post-surgical sometimes.", prep_tips: "Medical clearance if post-op.", aftercare: "Water; light activity." },
  { zone_id: "body", service_name: "Prenatal massage", description: "Side-lying safe pregnancy massage.", category: "massage", average_duration_minutes: 60, average_price_range: "$90–$150", finding_pros_filter: { serviceCategories: ["massage"], specialties: ["massage"], searchTerms: ["prenatal"] }, what_to_expect: "Certified therapist preferred.", prep_tips: "Doctor note if high-risk.", aftercare: "Hydrate; slow position changes." },
  { zone_id: "body", service_name: "Back facial", description: "Clarifying treatment for back skin.", category: "facials", average_duration_minutes: 50, average_price_range: "$75–$130", finding_pros_filter: { serviceCategories: ["facials"], specialties: ["skin"] }, what_to_expect: "Extract and mask for congestion.", prep_tips: "Wear open-back top if provided.", aftercare: "Clean sheets; breathable fabrics." },
  { zone_id: "feet", service_name: "Spa pedicure", description: "Soak, exfoliate, polish toes.", category: "nails_pedicure", average_duration_minutes: 60, average_price_range: "$45–$85", finding_pros_filter: { serviceCategories: ["nails_pedicure"], specialties: ["nail"] }, what_to_expect: "Massage and polish included.", prep_tips: "Open-toe shoes after.", aftercare: "Dry between toes well." },
  { zone_id: "feet", service_name: "Gel pedicure", description: "Long-wear toe color.", category: "nails_pedicure", average_duration_minutes: 60, average_price_range: "$50–$90", finding_pros_filter: { serviceCategories: ["nails_pedicure"], specialties: ["nail"] }, what_to_expect: "Gel cure on toes.", prep_tips: "No lotion on feet before.", aftercare: "Cuticle oil; professional removal." },
  { zone_id: "feet", service_name: "Reflexology", description: "Pressure points on feet.", category: "massage", average_duration_minutes: 45, average_price_range: "$55–$95", finding_pros_filter: { serviceCategories: ["massage"], searchTerms: ["reflexology"] }, what_to_expect: "Seated; focused on feet.", prep_tips: "Wear comfortable pants.", aftercare: "Water; rest if lightheaded." },
  { zone_id: "feet", service_name: "Medical pedicure", description: "Clinical foot care for nail/skin concerns.", category: "nails_pedicure", average_duration_minutes: 45, average_price_range: "$75–$150", finding_pros_filter: { serviceCategories: ["nails_pedicure"], specialties: ["nail"], searchTerms: ["medical pedicure"] }, what_to_expect: "Non-cosmetic focus; may refer out.", prep_tips: "List medications and diabetes status.", aftercare: "Follow technician home care." },
  { zone_id: "nails", service_name: "Russian manicure", description: "E-file cuticle refinement.", category: "nails_manicure", average_duration_minutes: 75, average_price_range: "$60–$110", finding_pros_filter: { serviceCategories: ["nails_manicure"], specialties: ["nail"] }, what_to_expect: "Precise cuticle work; long-lasting.", prep_tips: "Do not trim cuticles at home before.", aftercare: "Oil daily; avoid picking." },
  { zone_id: "nails", service_name: "Dip powder manicure", description: "Durable powder overlay.", category: "nails", average_duration_minutes: 60, average_price_range: "$45–$80", finding_pros_filter: { serviceCategories: ["nails"], specialties: ["nail"] }, what_to_expect: "Layers dipped and filed.", prep_tips: "Healthy nail plate preferred.", aftercare: "Professional removal only." },
];

export const SEED_BODY_SERVICES: BeautyBodyService[] = SERVICE_ROWS.map((r, i) => ({
  id: sid(i + 1),
  zone_id: r.zone_id,
  service_name: r.service_name,
  description: r.description,
  category: r.category,
  average_duration_minutes: r.average_duration_minutes,
  average_price_range: r.average_price_range,
  finding_pros_filter: r.finding_pros_filter,
  what_to_expect: r.what_to_expect,
  prep_tips: r.prep_tips,
  aftercare: r.aftercare,
}));
