import { CALIFORNIA_COSMETOLOGY_EXAM, CALIFORNIA_COSMETOLOGY_QUESTIONS } from "./california-cosmetology";
import { FLORIDA_COSMETOLOGY_EXAM, FLORIDA_COSMETOLOGY_QUESTIONS } from "./florida-cosmetology";
import { NEW_YORK_COSMETOLOGY_EXAM, NEW_YORK_COSMETOLOGY_QUESTIONS } from "./new-york-cosmetology";
import { PENNSYLVANIA_COSMETOLOGY_EXAM, PENNSYLVANIA_COSMETOLOGY_QUESTIONS } from "./pennsylvania-cosmetology";
import { TEXAS_COSMETOLOGY_EXAM, TEXAS_COSMETOLOGY_QUESTIONS } from "./texas-cosmetology";

export const PUBLISHED_EXAM_SEEDS = [
  { exam: TEXAS_COSMETOLOGY_EXAM, questions: TEXAS_COSMETOLOGY_QUESTIONS },
  { exam: CALIFORNIA_COSMETOLOGY_EXAM, questions: CALIFORNIA_COSMETOLOGY_QUESTIONS },
  { exam: FLORIDA_COSMETOLOGY_EXAM, questions: FLORIDA_COSMETOLOGY_QUESTIONS },
  { exam: NEW_YORK_COSMETOLOGY_EXAM, questions: NEW_YORK_COSMETOLOGY_QUESTIONS },
  { exam: PENNSYLVANIA_COSMETOLOGY_EXAM, questions: PENNSYLVANIA_COSMETOLOGY_QUESTIONS },
] as const;

export const TOTAL_PUBLISHED_QUESTIONS = PUBLISHED_EXAM_SEEDS.reduce(
  (sum, s) => sum + s.questions.length,
  0,
);
